# Config file for MagicCobblestoneGenerator add-on Version ${version}
# This config file is dynamic and saved when the server is shutdown.

commands:
  player:
    # Player main sub-command to access the addon.
    # This command label will be required to write after gamemode player command label, f.e. /[label] generator
    # Each alias must be separated with an empty space.
    main: generator
  admin:
    # Admin main sub-command to access the addon.
    # This command label will be required to write after gamemode admin command label, f.e. /[label] generator
    # Each alias must be separated with an empty space.
    main: generator

default-active-generators: 3

disabled-gamemodes: []