name: BentoBox-MagicCobblestoneGenerator
main: world.bentobox.magiccobblestonegenerator.StoneGeneratorPladdon
version: ${project.version}
api-version: "1.21"
folia-supported: true

authors: [BONNe, tastybento]
contributors: ["The BentoBoxWorld Community"]
website: https://bentobox.world
description: ${project.description}
