name: BentoBox-Level
main: world.bentobox.level.LevelPladdon
version: ${project.version}
api-version: "1.21"
folia-supported: true

authors: [tastybento]
contributors: ["The BentoBoxWorld Community"]
website: https://bentobox.world
description: ${project.description}
